apiVersion: v1
kind: Namespace
metadata:
  name: jbeatty-namespace
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: jbeatty-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
    imagePullPolicy: Always
      containers:
      - name: flask
        image: harleyguy/flaskapp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

        
---          